from .core import *
from .algorithms.zlib import Zlib
from .algorithms.lzma import Lzma
from .algorithms.lz4 import Lz4
from .algorithms.brotli import Brotli
from .algorithms.zstd import Zstd
from .algorithms.bz2 import Bz2
from .algorithms.snappy import Snappy
from .algorithms.implode import Implode
