#!/bin/sh -ef

DOCKER_ENGINE="${DOCKER_ENGINE:-podman}"

# Necessary on SELinux-enabled systems
EXTRA_ARGS="--security-opt label=disable"

print_usage()
{
	echo "Usage: $0 [-i] <full-target>/<variety>"
	echo
	echo "  -i                         enter container interactively, running bash"
	exit 1
}

if [ $# -gt 2 ]; then
	print_usage
elif [ $# -eq 2 ]; then
	if [ "$1" = "-i" ]; then
		EXTRA_ARGS="-it --entrypoint bash --security-opt label=disable"
		TARGET_DIR="$2"
	else
		print_usage
	fi
elif [ $# -eq 1 ]; then
	TARGET_DIR="$1"
else
	print_usage
fi

FULL_TARGET=$(echo "$TARGET_DIR" | cut -d/ -f1)
VARIETY=$(echo "$TARGET_DIR" | cut -d/ -f2)

case "$FULL_TARGET" in
cpp_stl_11)
	TARGET=cpp_stl
	SUBTARGET=_11
	;;
cpp_stl_98)
	TARGET=cpp_stl
	SUBTARGET=_98
	;;
*)
	TARGET="$FULL_TARGET"
	SUBTARGET=''
	;;
esac

cd $(dirname "$0")/../..
KAITAI_COMPRESS_DIR="$(pwd)"

echo "KAITAI_COMPRESS_DIR=$KAITAI_COMPRESS_DIR"

$DOCKER_ENGINE run --rm \
	-v "$KAITAI_COMPRESS_DIR:/kaitai_compress" \
	$EXTRA_ARGS \
	kaitai-compress-test-$TARGET$SUBTARGET-$VARIETY \
