#!/bin/sh -ef

DOCKER_ENGINE=podman
EXTRA_ARGS=
#EXTRA_ARGS="-it --entrypoint bash"

if [ $# -ne 1 ]; then
	echo "Usage: $0 <full-target>/<variety>"
	exit 1
fi

FULL_TARGET=$(echo "$1" | cut -d/ -f1)
VARIETY=$(echo "$1" | cut -d/ -f2)

case "$FULL_TARGET" in
cpp_stl_11)
	TARGET=cpp_stl
	SUBTARGET=_11
	;;
cpp_stl_98)
	TARGET=cpp_stl
	SUBTARGET=_98
	;;
*)
	TARGET="$FULL_TARGET"
	SUBTARGET=''
	;;
esac

cd $(dirname "$0")/../..
KAITAI_COMPRESS_DIR="$(pwd)"

echo "KAITAI_COMPRESS_DIR=$KAITAI_COMPRESS_DIR"

$DOCKER_ENGINE run --rm \
	-v "$KAITAI_COMPRESS_DIR:/kaitai_compress" \
	$EXTRA_ARGS \
	kaitai-compress-test-$TARGET$SUBTARGET-$VARIETY \
