name: kaitai_compress

on: [push]

jobs:
  base_container_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install kaitai-struct-compiler
        run: |
          sudo apt-get update
          curl -fsSL -O https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.9/kaitai-struct-compiler_0.9_all.deb
          sha256sum --check --warn .github/checksums
          sudo apt-get install ./kaitai-struct-compiler_0.9_all.deb
          ksc --version
      - name: Compile ksy into target languages
        working-directory: _test
        run: ./compile-ksy
      - name: Upload target language compilation results
        uses: actions/upload-artifact@v2
        with:
          name: targets
          path: _test/compiled
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kaitai/kaitai-compress-test-base-ubuntu_18.04
      - name: Build and export base-ubuntu_18.04
        uses: docker/build-push-action@v2
        with:
          context: _test/docker/base/ubuntu_18.04
          file: _test/docker/base/ubuntu_18.04/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=oci,dest=/tmp/kaitai-compress-test-base-ubuntu_18.04.tar
      - name: List images
        run: docker images
      - name: Upload base-ubuntu_18.04
        uses: actions/upload-artifact@v2
        with:
          name: base-ubuntu_18.04
          path: /tmp/kaitai-compress-test-base-ubuntu_18.04.tar
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build all Docker images
        working-directory: _test/docker
        run: DOCKER_ENGINE=docker ./build-images

      - name: Test on javascript/nodejs14
        working-directory: _test/docker
        run: DOCKER_ENGINE=docker ./dockerci javascript/nodejs14

      - name: Test on python/3.6
        working-directory: _test/docker
        run: DOCKER_ENGINE=docker ./dockerci python/3.6

      - name: Test on ruby/2.5
        working-directory: _test/docker
        run: DOCKER_ENGINE=docker ./dockerci ruby/2.5
  nodejs14:
    runs-on: ubuntu-latest
    needs: base_container_build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download target language compilation results
        uses: actions/download-artifact@v4.1.7
        with:
          name: targets
          path: _test/compiled
      - name: Download base-ubuntu_18.04
        uses: actions/download-artifact@v4.1.7
        with:
          name: base-ubuntu_18.04
          path: /tmp # downloads /tmp/kaitai-compress-test-base-ubuntu_18.04.tar
      - name: Load base-ubuntu_18.04
        run: docker load --input /tmp/kaitai-compress-test-base-ubuntu_18.04.tar
      - name: List images
        run: docker images
      - name: Build Docker image for javascript/nodejs14
        working-directory: _test/docker
        run: DOCKER_ENGINE=docker ./build-images javascript/nodejs14
      - name: Test on javascript/nodejs14
        working-directory: _test/docker
        run: DOCKER_ENGINE=docker ./dockerci javascript/nodejs14
