#!/bin/sh

for I in uncompressed/*.dat; do
	BASE=$(basename "$I" | sed 's/\.dat$//')

	echo "$BASE.lz4"
	lz4 -9 <$I >compressed/$BASE.lz4

	echo "$BASE.zlib"
	ruby -e 'require "zlib"; $stdout.write(Zlib::deflate($stdin.read))' <$I >compressed/$BASE.zlib

	echo "$BASE.lzma"
	xz --format=lzma <$I >compressed/$BASE.lzma

	echo "$BASE.xz"
	xz --format=xz <$I >compressed/$BASE.xz

	echo "$BASE.lzma_raw"
	xz --format=raw <$I >compressed/$BASE.lzma_raw
done
