#!/usr/bin/env ruby

require 'rspec'

$LOAD_PATH << 'compiled/ruby'
$LOAD_PATH << '../ruby/lib'

ALGORITHMS = [
  {:alg_name => 'lz4', :ext => 'lz4', :class_name => 'TestLz4'},
  {:alg_name => 'lzma_lzma', :ext => 'lzma', :class_name => 'TestLzmaLzma'},
  {:alg_name => 'lzma_xz', :ext => 'xz', :class_name => 'TestLzmaXz'},
  {:alg_name => 'zlib', :ext => 'zlib', :class_name => 'TestZlib'},
  {:alg_name => 'zstd', :ext => 'zst', :class_name => 'TestZstd'},
]

ALGORITHMS.each { |alg|
  name = alg[:alg_name]

  require "kaitai/compress/#{name}"
  require "test_#{name}"
  alg[:class] = Kernel::const_get(alg[:class_name])
}

Dir.glob('uncompressed/*.dat').each { |uncompressed_fn|
  name = File.basename(uncompressed_fn).gsub(/.dat$/, '')

  uncompressed_data = File.binread(uncompressed_fn)

  ALGORITHMS.each { |alg|
    context alg[:ext] do
      it "algorithm parses #{name}" do
        obj = alg[:class].from_file("compressed/#{name}.#{alg[:ext]}")
        expect(obj.body).to eq uncompressed_data
      end
    end
  }
}
