#!/usr/bin/env ruby

require 'rspec'

$LOAD_PATH << 'compiled/ruby'
$LOAD_PATH << '../ruby/lib'

require 'kaitai/compress/lz4'
require 'kaitai/compress/lzma_xz'
require 'kaitai/compress/zlib'
require 'kaitai/compress/zstd'

require 'test_lz4'
require 'test_lzma_xz'
require 'test_zlib'
require 'test_zstd'

Dir.glob('uncompressed/*.dat').each { |uncompressed_fn|
  name = File.basename(uncompressed_fn).gsub(/.dat$/, '')

  uncompressed_data = File.binread(uncompressed_fn)

  context 'lz4' do
    it "parses #{name}" do
      obj = TestLz4.from_file("compressed/#{name}.lz4")
      expect(obj.body).to eq uncompressed_data
    end
  end

  context 'zlib' do
    it "parses #{name}" do
      obj = TestZlib.from_file("compressed/#{name}.zlib")
      expect(obj.body).to eq uncompressed_data
    end
  end

  context 'lzma_xz' do
    it "parses #{name}" do
      obj = TestLzmaXz.from_file("compressed/#{name}.xz")
      expect(obj.body).to eq uncompressed_data
    end
  end

  context 'zstd' do
    it "parses #{name}" do
      obj = TestZstd.from_file("compressed/#{name}.zst")
      expect(obj.body).to eq uncompressed_data
    end
  end
}
